#!/bin/sh

hflg=0

while getopts h opt ;do
	case $opt in
		h)hflg=1;;
	esac
done

if test $hflg -eq 1 ;then
	echo 'Usage: You have to edit this.'
	exit 0
fi

list=$(ls -1)
for var in $list ;do
	sed -e 's@\~\/bin@$HOME\/miyagawtools@g' -i $var
done
