#!/bin/sh

hflg=0

#if test $# -eq 0 ;then
#	hflg=1
#fi

while getopts h opt ;do
	case $opt in
		h)hflg=1;;
	esac
done
shift $(($OPTIND - 1))

if test $hflg -eq 1 ;then
	echo "Usage: bkup"
	exit 0
fi

rsync -auv ~/bin/ /mnt/windows/bk/bin/
rsync -auv ~/ctf/ /mnt/windows/bk/ctf/
rsync -auv ~/Desktop/ /mnt/windows/bk/Desktop/
rsync -auv ~/Documents/ /mnt/windows/bk/Documents/
rsync -auv ~/Downloads/ /mnt/windows/bk/Downloads/
rsync -auv ~/neosnippets/ /mnt/windows/bk/neosnippets/
rsync -auv ~/peda/ /mnt/windows/bk/peda/
rsync -auv ~/rc/ /mnt/windows/bk/rc/
rsync -auv ~/tmp/ /mnt/windows/bk/tmp/
