#!/bin/bash
for arg in $@ ;do
	now=`pwd`
	mkdir $arg
	if test `echo $arg | grep '/'` ;then
		location=$arg
		arg=`basename ${arg}`
		echo "alias "${arg}"='cd "${location}"'" >> ~/bin/cdir
	else
		location=${now}'/'${arg}'/'
		echo "alias "${arg}"='cd "${location}"'" >> ~/bin/cdir
	fi
done
source ~/.bashrc
