#!/bin/bash

if test "$1" = "-h" ;then
	echo "Usage: dirmk file"
	exit 0
fi

for arg in $@ ;do
	now=`pwd`
	mkdir $arg
	if test `echo $arg | grep '/'` ;then
		location=$arg
		arg=`basename ${arg}`
		echo "alias "${arg}"='cd "${location}"'" >> $HOME/Documents/cdir/cdir
	else
		location=${now}'/'${arg}'/'
		echo "alias "${arg}"='cd "${location}"'" >> $HOME/Documents/cdir/cdir
	fi
done
exec /bin/bash
