#!/bin/sh

if test "$1" = "-h" ;then
	echo "Usage: dirrm file"
	exit 0
fi

for arg in $@ ;do
	now=`pwd`
	if test `echo $arg | grep '/'` ;then
		location=${arg}
		echo ue
		arg=`basename ${arg}`
		num=`grep -e ${now} -n $HOME/Documents/cdir/cdir | sed -e 's/:.*//g' | tail -1`
		sed -e ${num}d -i $HOME/Documents/cdir/cdir
	else
		location=$now'/'$arg
		num=`grep -e ${now} -n $HOME/Documents/cdir/cdir | sed -e 's/:.*//g' | tail -1`
		sed -e ${num}d -i $HOME/Documents/cdir/cdir
	fi
done
rm -r $location
exec /bin/bash
