#!/bin/sh

hflg=0
aflg=0
fflg=0
mflg=0
rflg=0
pflg=0
fflg=0
cflg=0

if test $# -eq 0 ;then
	hflg=1
fi

while getopts ham:rpf:c: opt ;do
	case $opt in
		h)hflg=1;;
		a)aflg=1;;
		m)mflg=1;marg=$OPTARG;;
		r)rflg=1;;
		p)pflg=1;;
		f)fflg=1;farg=$OPTARG;;
		c)cflg=1;carg=$OPTARG;;
	esac
done
shift $(($OPTIND - 1))

if test $hflg -eq 1 ;then
	echo "Usage: egit [option]
[+]UsageOption:
   f [file]: git add [file]
   m [comment]: git commit -m [comment]
   r [tag/URI]: git remote add origin [tag/URI]
   p: git push origin master"
	exit 0
fi

if test $aflg -eq 1 ;then
	git add .
	git status
	exit 0
fi

if test $mflg -eq 1 ;then
	git commit -m $marg
	exit 0
fi

if test $cflg -eq 1 ;then
	git add .
	git status
	git commit -m $carg
	exit 0
fi

if test $rflg -eq 1 ;then
	now=$(pwd)
	arg=$(basename ${now})
	git remote rm origin
	git remote add origin https://github.com/miyagaw61/${arg}
	exit 0
fi

if test $pflg -eq 1 ;then
	git push origin master
	exit 0
fi

if test $fflg -eq 1 ;then
	cecho -g    '#######################################'
	cecho -r -f -n '[+]'
	cecho -g -f ' add -> commit -> remote add -> push'
	cecho -g    '#######################################'
	git add .
	git status
	sleep 0.5
	git commit -m $farg
	sleep 0.5
	now=$(pwd)
	arg=$(basename ${now})
	git remote rm origin
	git remote add origin https://github.com/miyagaw61/${arg}.git
	sleep 0.5
	git push origin master
	exit 0
fi
