#!/bin/sh

hflg=0
aflg=0
fflg=0
mflg=0
rflg=0
pflg=0
fflg=0
cflg=0

if test $# -eq 0 ;then
	hflg=1
fi

while getopts ham:rpf:c: opt ;do
	case $opt in
		h)hflg=1;;
		a)aflg=1;;
		m)mflg=1;marg=$OPTARG;;
		r)rflg=1;;
		p)pflg=1;;
		f)fflg=1;farg=$OPTARG;;
		c)cflg=1;carg=$OPTARG;;
	esac
done
shift $(($OPTIND - 1))

if test $hflg -eq 1 ;then
	echo "Usage: egit [option]
[+]UsageOption:
   f [file]: git add [file]
   m [comment]: git commit -m [comment]
   r [tag/URI]: git remote add origin [tag/URI]
   p: git push origin master"
	exit 0
fi


if test $aflg -eq 1 ;then
	git add .
	git status
	exit 0
fi

if test $mflg -eq 1 ;then
	git commit -m $marg
	exit 0
fi

if test $cflg -eq 1 ;then
	git add .
	git status
	git commit -m $carg
	exit 0
fi

if test $rflg -eq 1 ;then
	now=$(pwd)
	arg=$(basename ${now})
	git remote rm origin
	git remote add origin https://github.com/miyagaw61/${arg}
	exit 0
fi

if test $pflg -eq 1 ;then
	git push origin master
	exit 0
fi

if test $fflg -eq 1 ;then
	cecho -g    '#######################################'
	cecho -r -f -n '[+]'
	cecho -g -f ' add -> commit -> remote add -> push'
	cecho -g    '#######################################'
	git add .
	git status
	sleep 0.5
	git commit -m $farg
	sleep 0.5
	now=$(pwd)
	arg=$(basename ${now})
	git remote rm origin
	git remote add origin https://github.com/miyagaw61/${arg}.git
	sleep 0.5
	git push origin master
	exit 0
fi

if test $1 = "miyagawtools" -o $1 = "mt" ;then
	sa
	args=$@
	args=$(echo $args | perl -pe 's/'$1'//g')
	if test $# -ge 2 ;then
		for var in $args ;do
			cp -a $var ~/git/miyagawtools/
		done
	fi
	cd ~/git/miyagawtools/
	exec /bin/bash
	exit 0
fi

if test $1 = "tmp" ;then
	sa
	args=$@
	args=$(echo $args | perl -pe 's/'$1'//g')
	if test $# -ge 2 ;then
		for var in $args ;do
			cp -a $var ~/git/tmp/
		done
	fi
	cd ~/git/tmp/
	exec /bin/bash
	exit 0
fi

if test $1 = "miyagawpeda" -o $1 = "mp" ;then
	sa
	args=$@
	args=$(echo $args | perl -pe 's/'$1'//g')
	if test $# -ge 2 ;then
		for var in $args ;do
			cp -a $var ~/git/miyagawpeda/
		done
	fi
	cd ~/git/miyagawpeda/
	exec /bin/bash
	exit 0
fi

if test $1 = "miyagaw61.github.io" -o $1 = "github.io" -o $1 = "io" ;then
	sa
	args=$@
	args=$(echo $args | perl -pe 's/'$1'//g')
	if test $# -ge 2 ;then
		for var in $args ;do
			cp -a $var ~/git/miyagaw61.github.io/
		done
	fi
	cd ~/git/miyagaw61.github.io/
	exec /bin/bash
	exit 0
fi

if test $1 = "clone" ;then
	if test $# -eq 3 ;then
		git clone "http://github.com/"$2"/"$3".git"
	elif test $# -eq 4 ;then
		git clone "http://github.com/"$2"/"$3".git "$4
	elif test $# -eq 1 ;then
		echo -n "UserName: "
		read username
		echo -n "Repository: "
		read repository
		echo -n "Directory: "
		read directory
		git clone "http://github.com/"$username"/"$repository".git" $directory
	fi
fi
