#!/bin/sh

hflg=0
if test $# -eq 0 ;then
	hflg=1
fi

for arg in "$@" ;do
	if test "$arg" = "-h" -o "$arg" = "--help" -o "$arg" = "help" ;then
		hflg=1
	fi
done

if test $hflg -eq 1 ;then
	echo -n "Usage: engmemo [ [word][jp] ] [ sentence [sentence][jp] ]
"
	exit 0
fi

if test "$1" = "sentence" ;then
    echo "|"$2" | "$3"|" >> $HOME/Documents/engmemo/sentence.engmemo
else
    echo "|"$1" | "$2"|" >> $HOME/Documents/engmemo/word.engmemo
fi

