#!/bin/sh
hflg=0
sflg=0
sarg=''
while getopts hs: opt ;do
	case $opt in
		h)hflg=1;;
	s)sflg=1; sarg=$OPTARG;;
	esac
done

if [ $hflg -eq 1 ]; then
	echo 'Usage: gc [C_file] [option]
[+]UsageOptions:
   nodep/nonx
   norelro
   nossp
   onpie
   [C_file]'
	exit 0
fi

options=""

if test $# -ge 2 ;then
	for var in $@ ;do
		if test $var = "nodep" -o $var = "nonx" ;then
			options=$options" -z execstack"
		elif test $var = "norelro" ;then
			options=$options" -Wl, -z, relro, -z, now"
		elif test $var = "nossp" ;then
			options=$options" -fno-stack-protector"
		elif test $var = "onpie" ;then
			options=$options" -fPIE -pie"
		else
			file=$var
		fi
	done
fi

if test $# -eq 1 ;then
	file=$1
fi

out=$(echo $1 | sed -E 's/(.*).c/\1/')
allrm $out
gcc -I ~/bin/include/ $options -o $out $file

