#!/bin/sh

hflg=0
sflg=0

while getopts hs opt ;do
	case $opt in
		h)hflg=1;;
		s)sflg=1;;
	esac
done

if test $hflg -eq 1 ;then
	echo 'Usage: gcat [file_name] / gcat -s\n -s: gdb_socat'
	exit 0
fi

if test $sflg -eq 1 ;then
	pid=`ps u | grep 'socat' | grep 'TCP' | sed -E 's/^[^0-9]*([0-9][^\ ]*).*/\1/'`
	gdb -p ${pid}
	exit 0
fi

#pid=$(ps x | grep 'socat' | grep $1 | grep -P -o '\d+\s')
pid=$(ps x |grep -v 'gcat' | grep -v 'grep' | grep $1 | tail -1)
pid=$(echo $pid | sed -E 's/([0-9]+).*/\1/g')
echo $pid
gdb -p $pid
