#!/bin/sh

nflg=1
hflg=0
dflg=0
xflg=0
oflg=0
aflg=0

#if test $# -eq 0 ;then
#	hflg=1
#fi

while getopts hdxoa opt ;do
	case $opt in
		h)hflg=1;;
		d)dflg=1;nflg=0;;
		x)xflg=1;nflg=0;;
		o)oflg=1;nflg=0;;
		a)aflg=1;;
	esac
done
shift $(($OPTIND - 1))

if test $hflg -eq 1 ;then
	echo "Usage: getfile [option]
[+]UsageOption:
   d: dir
   x: exe
   o: others
   a: all"
	exit 0
fi

if test $nflg -eq 1 ;then
	if test $aflg -eq 1 ;then
		ls -a1F > $HOME/Documents/git/mgtools/.tmp/all.tmp
		cat $HOME/Documents/git/mgtools/.tmp/all.tmp | grep -P -v -e '.*(?=\*$)'
		allrm $HOME/Documents/git/mgtools/.tmp/all.tmp
		exit 0
	else
        #dir
        #ls -1F | grep -oP '.*(?=\/$)'
        ls -1F | grep -oP '.*/$'
        #exe
        ls -1F | grep -oP '.*(?=\*$)' 
        #others
        ls -1F > $HOME/Documents/git/mgtools/.tmp/all.tmp
        cat $HOME/Documents/git/mgtools/.tmp/all.tmp | grep -P -v -e '.*(?=\/$)' | grep -P -v -e '.*(?=\*$)'
        allrm $HOME/Documents/git/mgtools/.tmp/all.tmp
        exit 0
    fi
fi

if test $dflg -eq 1 ;then
	if test $aflg -eq 0 ;then
		ls -1F | grep -oP '.*/$'
	else
		ls -a1F | grep -oP '.*/$'
	fi
	allrm $HOME/Documents/git/mgtools/.tmp/all.tmp
fi

if test $xflg -eq 1 ;then
	if test $aflg -eq 0 ;then
		ls -1F | grep -oP '.*(?=\*$)' 
	else
		ls -a1F | grep -oP '.*(?=\*$)' 
	fi
	allrm $HOME/Documents/git/mgtools/.tmp/all.tmp
fi

if test $oflg -eq 1 ;then
	if test $aflg -eq 0 ;then
		ls -1F > $HOME/Documents/git/mgtools/.tmp/all.tmp
	else
		ls -a1F > $HOME/Documents/git/mgtools/.tmp/all.tmp
	fi
	cat $HOME/Documents/git/mgtools/.tmp/all.tmp | grep -P -v -e '.*(?=\/$)' | grep -P -v -e '.*(?=\*$)'
	allrm $HOME/Documents/git/mgtools/.tmp/all.tmp
fi

