#!/bin/sh

hflg=0
aflg=0
fflg=0
mflg=0
rflg=0
pflg=0
fflg=0
cflg=0

if test $# -eq 0 ;then
	hflg=1
elif test $1 = "help" ;then
	hflg=1
fi

while getopts ha:m:rpf:c: opt ;do
	case $opt in
		h)hflg=1;;
		a)aflg=1;aarg=$OPTARG;;
		m)mflg=1;marg=$OPTARG;;
		r)rflg=1;;
		p)pflg=1;;
		f)fflg=1;farg=$OPTARG;;
		c)cflg=1;carg=$OPTARG;;
	esac
done
shift $(($OPTIND - 1))

if test $hflg -eq 1 ;then
	echo -n "Usage: git2 [clone] [add [file]] [branch] [m]
            [branch [existed_branch]] [branch -a] [branch rmremote] [branch [not_existed_branch]]
            [commit] [merge [branch]] [push [branch]] [cm [branch]] [cp [branch]]
            [cmp [branch]] [ac [file]] [acm [file] [branch]] [acp [file] [branch]]
            [acmp [file] [branch]] [rmindex] [add_alias]
 clone : _____________________ super clone
 status: _____________________ super status
 add [file]: _________________ super add
 diff [file]: ________________ super diff
 m : _________________________ commit message memo
 branch: _____________________ show branch
 branch -a: __________________ show branch all
 branch -d [branch]: _________ delete branch
 branch [existed_branch]: ____ checkout
 branch [not_existed_branch]:_ create branch -> checkout
 branch rmremote: ____________ git remote prune origin
 commit: _____________________ super commit
 merge [branch]: _____________ checkout -> merge preview_branch -> checkout preview_branch
 push [branch]: ______________ checkout [branch] -> push -> checkout preview_branch
 cm [branch]: ________________ git2 commit -> git2 merge [branch]
 cp [branch]: ________________ git2 commit -> git2 push [branch]
 cmp [branch]: _______________ git2 commit -> git2 merge [branch] -> git2 push
 mp [branch]: ________________ git2 merge [branch] -> git2 push
 ac [file]: __________________ git2 add [file] -> git2 commit
 acm [file] [branch]: ________ git2 add [file] -> git2 commit -> git2 merge [branch]
 acp [file] [branch]: ________ git2 add -> git2 commit -> git2 push
 acmp [file] [branch]: _______ git2 add [file] -> git2 commit -> git2 merge [branch] -> git2 push
 rmindex [file]: _____________ git2 rm --cache [file]
 add_alias: __________________ add aliases to $HOME/.bashrc ( You have to check below. )

 [+]You can use these default aliases:
 s: status
 a: add
 b: branch
 c: commit
 m: merge / memo (argcheck)
 p: push

 [+]You can use these after use add_alias option:
 gi:     git2
 gis:    git2 status
 gif     git2 diff
 gia:    git2 add
 gic:    git2 commit
 gim:    git2 merge / git2 memo (argcheck)
 gip:    git2 push
 gib:    git2 branch
 gicm:   git2 cm
 gicp:   git2 cp
 gicmp:  git2 cmp
 gimp:   git2 mp
 giac:   git2 ac
 giacm:  git2 acm
 giacp:  git2 acp
 giacmp: git2 acmp
 "
	allrm branch.tmp now.tmp
    allrm $HOME/mgtools/.tmp/git2.m
	exit 0
fi

branchsave(){
	git branch > branch.tmp
	cat branch.tmp | grep -E "\*" | perl -pe "s@\*(.*)@\1@g" > now.tmp
}

if test "$1" = "add_alias" ;then
	if test ! "$(cat $HOME/.bashrc | grep 'alias for git2')" ;then
		echo -n "\n#alias for git2
alias gi='git2'
alias gis='git2 status'
alias gim='git2 m'
alias gif='git2 diff'
alias gia='git2 add'
alias gic='git2 commit'
alias gim='git2 merge'
alias gip='git2 push'
alias gib='git2 branch'
alias gicm='git2 cm'
alias gicmp='git2 cmp'
alias gimp='git2 mp'
alias giac='git2 ac'
alias giacm='git2 acm'
alias giacmp='git2 acmp'\n
" >> $HOME/.bashrc
	fi
    allrm $HOME/mgtools/.tmp/git2.m
	exit 0
fi

if test $1 = "diff" ;then
  for var in $@ ;do
    if test $var != $1 ;then
      git diff $var
    fi
  done
  exit 0
fi
      
if test $1 = "add" -o $1 = "a" ;then
	git branch
	for var in $@ ;do
		if test ! $var = "add" -o ! $var = "a" ;then
			git add $var
		fi
	done
	git status
	allrm branch.tmp now.tmp
	exit 0
fi

if test $1 = "status" -o $1 = "s" ;then
	git branch
	git status
	allrm branch.tmp now.tmp
	exit 0
fi

if test $1 = "commit" -o $1 = "c" ;then
	git status
	branchsave
    vim $HOME/mgtools/.tmp/git2.m
    msg="$(cat $HOME/mgtools/.tmp/git2.m)"
    message="$msg"
    if test $# -le 2 ;then
        message=""
        for var in $msg ;do
            case $var in
            bugfix)message="[bugfix]$file :";;
            bug)message="[bugfix]$file :";;
            b)message="[bugfix]$file :";;
            update)message="[update]$file :";;
            up)message="[update]$file :";;
            u)message="[update]$file :";;
            new)message="[new]$file :";;
            n)message="[new]$file :";;
            new)message="[new]$file :";;
            add)message="[add]$file :";;
            a)message="[add]$file :";;
            del)message="[delete]$file :";;
            d)message="[delete]$file :";;
            *)message="${message} ${var}";;
            esac
        done
    fi
    echo $message
	git commit -m "$message"
	echo "\n[+]COMMIT FINISH!\n"
	allrm branch.tmp now.tmp
    allrm $HOME/mgtools/.tmp/git2.m
	exit 0
fi

if test "$1" = "cp" -o "$1" = "commitpush" ;then
	git2 commit
	if test $# -eq 1 ;then
		echo -n "\n[+]push master,OK? (y/n) : "
		read ans
		if test "$ans" != "n" ;then
			git2 push master
		else
			echo "\n[+]push stop.\n"
		fi
	else
		git2 push $2
	fi
    allrm $HOME/mgtools/.tmp/git2.m
	exit 0
fi

if test "$1" = "addcommit" -o "$1" = "ac" ;then
	git branch
  arglst=$(echo $@ | perl -pe 's/'$1'//g')
	git add $arglst
  file=$2
	git status
	branchsave
    vim $HOME/mgtools/.tmp/git2.m
    msg="$(cat $HOME/mgtools/.tmp/git2.m)"
    message="$msg"
    if test $# -eq 2 ;then
        message=""
        for var in $msg ;do
            case $var in
            bugfix)message="[bugfix]$file :";;
            bug)message="[bugfix]$file :";;
            b)message="[bugfix]$file :";;
            update)message="[update]$file :";;
            up)message="[update]$file :";;
            u)message="[update]$file :";;
            new)message="[new]$file :";;
            n)message="[new]$file :";;
            new)message="[new]$file :";;
            add)message="[add]$file :";;
            a)message="[add]$file :";;
            del)message="[delete]$file :";;
            d)message="[delete]$file :";;
            *)message="${message} ${var}";;
            esac
        done
    fi
    echo $message
	git commit -m "$message"
	echo "\n[+]COMMIT FINISH!\n"
	allrm branch.tmp now.tmp
    allrm $HOME/mgtools/.tmp/git2.m
	exit 0
fi

if test "$1" = "acp" -o "$1" = "addcommitpush" ;then
    if test $# -le 2 ;then
        echo "Usage: git2 acp [file] [branch]"
        allrm $HOME/mgtools/.tmp/git2.m
        exit 0
    fi
    git branch
    arglst=""
    fin="$(echo $@ | perl -pe 's@\s@/@g' | xargs basename)"
    for var in $@ ;do
        case $var in
            $1);;
            $fin);;
            *)arglst=${arglst}" "${var}
        esac
    done
    git add $arglst
    file=$2
    git status
    branchsave
    msg=""
    vim $HOME/mgtools/.tmp/git2.m
    msg="$(cat $HOME/mgtools/.tmp/git2.m)"
    message="$msg"
    if test $# -eq 3 ;then
        message=""
        for var in $msg ;do
            case $var in
                bugfix)message="[bugfix]$file :";;
                bug)message="[bugfix]$file :";;
                b)message="[bugfix]$file :";;
                update)message="[update]$file :";;
                up)message="[update]$file :";;
                u)message="[update]$file :";;
                new)message="[new]$file :";;
                n)message="[new]$file :";;
                new)message="[new]$file :";;
                add)message="[add]$file :";;
                a)message="[add]$file :";;
                del)message="[delete]$file :";;
                d)message="[delete]$file :";;
                *)message="${message} ${var}";;
            esac
        done
    fi
    git commit -m "$message"
    echo "\n[+]COMMIT FINISH!\n"
    branch=$3
    if test "$3" = "master" -o "$3" = "m" ;then
        branch="master"
    fi
    git2 push $branch
    allrm $HOME/mgtools/.tmp/git2.m
    exit 0
fi

if test "$1" = "acm" -o "$1" = "addcommitmerge" ;then
	git branch
  arglst=""
  fin="$(echo $@ | perl -pe 's@\s@/@g' | xargs basename)"
  for var in $@ ;do
    case $var in
      $1);;
      $fin);;
      *)arglst=${arglst}" "${var}
    esac
  done
	git add $arglst
  file=$2
	git status
	branchsave
	msg=""
    vim $HOME/mgtools/.tmp/git2.m
    msg="$(cat $HOME/mgtools/.tmp/git2.m)"
  message="$msg"
  if test $# -eq 3 ;then
    message=""
    for var in $msg ;do
      case $var in
        bugfix)message="[bugfix]$file :";;
        bug)message="[bugfix]$file :";;
        b)message="[bugfix]$file :";;
        update)message="[update]$file :";;
        up)message="[update]$file :";;
        u)message="[update]$file :";;
        new)message="[new]$file :";;
        n)message="[new]$file :";;
        new)message="[new]$file :";;
        add)message="[add]$file :";;
        a)message="[add]$file :";;
        del)message="[delete]$file :";;
        d)message="[delete]$file :";;
        *)message="${message} ${var}";;
      esac
    done
  fi
	git commit -m "$message"
	echo "\n[+]COMMIT FINISH!\n"
	if test $2 = "master" -o $2 = "m" ;then
		echo -n "\n[+]merge master,OK? (y/n) : "
		read ans
		if test "$ans" != "n" ;then
			git checkout master
		else
			echo "\n[+]merge stop.\n"
			git branch
			allrm branch.tmp now.tmp
            allrm $HOME/mgtools/.tmp/git2.m
			exit 0
		fi
	else
		git checkout $3
	fi
	git merge $(cat now.tmp)
	git checkout $(cat now.tmp)
	git branch
	allrm branch.tmp now.tmp
    allrm $HOME/mgtools/.tmp/git2.m
	exit 0
fi

if test "$1" = "acmp" -o "$1" = "addcommitmergepush" ;then
	git branch
  arglst=""
  fin="$(echo $@ | perl -pe 's@\s@/@g' | xargs basename)"
  for var in $@ ;do
    case $var in
      $1);;
      $fin);;
      *)arglst=${arglst}" "${var}
    esac
  done
	git add $arglst
  file=$2
	git status
	branchsave
	msg=""
    vim $HOME/mgtools/.tmp/git2.m
    msg="$(cat $HOME/mgtools/.tmp/git2.m)"
  message="$msg"
  if test $# -eq 3 ;then
    message=""
    for var in $msg ;do
      case $var in
        bugfix)message="[bugfix]$file :";;
        bug)message="[bugfix]$file :";;
        b)message="[bugfix]$file :";;
        update)message="[update]$file :";;
        up)message="[update]$file :";;
        u)message="[update]$file :";;
        new)message="[new]$file :";;
        n)message="[new]$file :";;
        new)message="[new]$file :";;
        add)message="[add]$file :";;
        a)message="[add]$file :";;
        del)message="[delete]$file :";;
        d)message="[delete]$file :";;
        *)message="${message} ${var}";;
      esac
    done
  fi
	git commit -m "$message"
	echo "\n[+]COMMIT FINISH!\n"
	if test $2 = "master" -o $2 = "m" ;then
		echo -n "\n[+]merge&push master,OK? (y/n) : "
		read ans
		if test "$ans" != "n" ;then
			git checkout master
			git merge $(cat now.tmp)
			git push
			git checkout $(cat now.tmp)
		else
			echo "\n[+]merge&push stop.\n"
			allrm branch.tmp now.tmp
            allrm $HOME/mgtools/.tmp/git2.m
			exit 0
		fi
	else
		git checkout $3
		git merge $(cat now.tmp)
		git push
		git checkout $(cat now.tmp)
	fi
	allrm branch.tmp now.tmp
    allrm $HOME/mgtools/.tmp/git2.m
	exit 0
fi


if test "$1" = "merge" -o "$1" = "m" ;then
    if test $# -eq 1 ;then
        git2 memo
        exit 0
    fi
	branchsave
	#if test $# -eq 1 ;then
	#	echo -n "\n[+]merge master,OK? (y/n) : "
	#	read ans
	#	if test "$ans" != "n" ;then
	#		git checkout master
	#	else
	#		echo "\n[+]merge stop.\n"
	#		allrm branch.tmp now.tmp
    #        allrm $HOME/mgtools/.tmp/git2.m
	#		exit 0
	#	fi
	#else
	#	git checkout $2
	#fi
    branch=$2
    if test "$2" = "m" ;then
        branch="master"
    fi
    git checkout $branch
	git merge $(cat now.tmp)
	git checkout $(cat now.tmp)
	allrm branch.tmp now.tmp
	exit 0
fi

if test $1 = "push" -o $1 = "p" ;then
	if test "$(png github.com)" = "OK" ;then
        if test ! $# -eq 2 ;then
            echo "Usage: git2 push [branch]"
            exit 0
        fi
        branch=$2
        if test "$2" = "m" ;then
            branch="master"
        fi
		git branch
		echo "\n[+]PUSH : origin "${branch}"\n"
		branchsave
        echo -n "\n[+]push "${branch}", OK? (y/n) : "
        read ans
        if test "$ans" != "n" ;then
            git checkout $branch
        else
            echo "\n[+]push stop.\n"
            allrm branch.tmp now.tmp
            exit 0
        fi
		git push origin $branch
		git checkout $(cat now.tmp)
		git branch
		allrm branch.tmp now.tmp
	fi
	exit 0
fi

if test "$1" = "branch" -o "$1" = "b" ;then
	branchsave
	if test $# -eq 1 ;then
		git branch
	fi
	if test $# -ge 2 ;then
		if test "$2" = "-a" ;then
			git branch -a
		elif test "$2" = "rmremote" ;then
			git remote prune origin
		elif test "$2" = "-d" ;then
			git branch -d $3
		elif test ! "$(cat branch.tmp | grep $2)" ;then
			git branch $2
			git checkout $2
			git branch
		else
			git branch
			echo '\n[+]GIT CHECKOUT\n'
			git checkout $2
			git branch
		fi
	fi
	allrm branch.tmp now.tmp
	exit 0
fi

if test "$1" = "cm" -o "$1" = "commitmerge" ;then
	git2 commit
	if test $# -eq 1 ;then
		echo -n "\n[+]push master,OK? (y/n) : "
		read ans
		if test "$ans" != "n" ;then
			git2 merge master
		else
			echo "\n[+]merge stop.\n"
		fi
	else
		git2 merge $2
	fi
	allrm branch.tmp now.tmp
    allrm $HOME/mgtools/.tmp/git2.m
	exit 0
fi

if test "$1" = "cmp" -o "$1" = "commitmergepush" ;then
	git2 commit
	if test $# -eq 1 ;then
		echo -n "\n[+]merge&push master,OK? (y/n) : "
		read ans
		if test "$ans" != "n" ;then
			git2 merge master
			git2 push master
		else
			echo "\n[+]merge&push stop.\n"
		fi
	else
		git2 merge $2
		git2 push $2
	fi
	allrm branch.tmp now.tmp
    allrm $HOME/mgtools/.tmp/git2.m
	exit 0
fi

if test "$1" = "mp" -o "$1" = "mergepush" ;then
	if test $# -eq 1 ;then
		echo -n "\n[+]merge&push master,OK? (y/n) : "
		read ans
		if test "$ans" != "n" ;then
			git2 merge master
			git2 push master
		else
			echo "\n[+]merge&push stop.\n"
		fi
	else
		git2 merge $2
		git2 push $2
	fi
	allrm branch.tmp now.tmp
	exit 0
fi

if test $1 = "rmindex" ;then
  arglst=$(echo $@ | perl -pe 's/'$1'//g')
	git rm --cache -r $arglst
	allrm branch.tmp now.tmp
	exit 0
fi

if test $1 = "clone" ;then
	if test $# -eq 3 ;then
		git clone "http://github.com/"$2"/"$3".git"
	elif test $# -eq 4 ;then
		git clone "http://github.com/"$2"/"$3".git "$4
	elif test $# -eq 1 ;then
		echo -n "UserName: "
		read username
		echo -n "Repository: "
		read repository
		echo -n "Directory: "
		read directory
		git clone "http://github.com/"$username"/"$repository".git" $directory
	fi
	allrm branch.tmp now.tmp
	exit 0
fi

if test $1 = "remote"  -o $1 = "r" ;then
	now=$(pwd)
	arg=$(basename ${now})
	echo -n username:
	read user
	git remote rm origin
	git remote add origin https://github.com/${user}/${arg}
	allrm branch.tmp now.tmp
	exit 0
fi

if test "$1" = "m" -o "$1" = "memo" ;then
    vim $HOME/mgtools/.tmp/git2.m
    exit 0
fi
