#!/bin/sh

hflg=0

#if test $# -eq 0 ;then
#	hflg=1
#fi

while getopts h opt ;do
	case $opt in
		h)hflg=1;;
	esac
done
shift $(($OPTIND - 1))

if test $hflg -eq 1 ;then
	echo "Usage: "
	exit 0
fi

sa
pid=$(ps u | grep /bin/bash | grep -v 'grep' | perl -pe 's/[^\s]*\s*([^\s]*).*/ \1 /g')
for var in $pid ;do
	kill -9 $var
done
