#!/bin/sh

hflg=0
#if test $# -eq 0 ;then
#	hflg=1
#fi

aflg=0
varA=""
for arg in "$@" ;do
	if test "$arg" = "-h" -o "$arg" = "--help" -o "$arg" = "help" ;then
		hflg=1

	elif test $aflg -eq 1 ;then
		varA=$arg
		aflg=0

	elif test "$arg" = "-a" ;then
		aflg=1

	fi
done

if test $hflg -eq 1 ;then
	echo -n "Usage: al2jp [file]
"
	exit 0
fi

lst=$(echo $1 | perl -pe 's@(.)@\1 @g')
aflg=0
dflg=0
xflg=0
oflg=0
for var in $lst ;do
    case $var in
    d) dflg=1;;
    x) xflg=1;;
    o) oflg=1;;
    a) aflg=1;;
    esac
done
for var in $@ ;do
    case $var in
    d) dflg=1;;
    x) xflg=1;;
    o) oflg=1;;
    a) aflg=1;;
    esac
done

##############################
if test $aflg -eq 1 ;then
#-----------------------------
if test $dflg -eq 1 ;then
    echo "$(cecho -bf $(getfile -ad))" | fzf --reverse --ansi
fi
if test $xflg -eq 1 ;then
    echo "$(cecho -gf $(getfile -ax))" | fzf --reverse --ansi
fi
if test $oflg -eq 1 ;then
    getfile -ao | fzf --reverse --ansi
fi
if test $dflg -eq 0 -a $xflg -eq 0 -a $oflg -eq 0 ;then
    echo "$(cecho -bf $(getfile -ad))""\n""$(cecho -gf $(getfile -ax))""\n""$(getfile -ao)" | fzf --reverse --ansi
fi
exit 0
#-----------------------------
fi
##############################

if test $dflg -eq 1 ;then
    echo "$(cecho -bf $(getfile -d))" | fzf --reverse --ansi
fi
if test $xflg -eq 1 ;then
    echo "$(cecho -gf $(getfile -x))" | fzf --reverse --ansi
fi
if test $oflg -eq 1 ;then
    getfile -o | fzf --reverse --ansi
fi
if test $# -eq 0 ;then
    echo "$(cecho -bf $(getfile -d))""\n""$(cecho -gf $(getfile -x))""\n""$(getfile -o)" | fzf --reverse --ansi
fi
