#!/bin/bash

hflg=0

if test $# -eq 0 ;then
	hflg=1
fi

while getopts h opt ;do
	case $opt in
		h)hflg=1;;
	esac
done

if [ $hflg -eq 1 ]; then
	echo 'Usage: middle [file_name] [start_line] [end_line]'
	exit 0
fi

ln=$(cat $1 | wc -l)
if test $2 -gt $ln ;then
    exit 0
fi
head -n $3 $1 | tail -n $(($3 - $2 + 1))
