#!/bin/sh

hflg=0
if test $# -eq 0 ;then
	hflg=1
fi

case $1 in
-h)hflg=1;;
esac

if test $hflg -eq 1 ;then
	echo -n "Usage: mkmemo 
"
	exit 0
fi

if test $EDITOR ;then
    $EDITOR ~/git/miyagaw61.github.io/_posts/$(date -Idate)-$1\.md
else
    vim ~/git/miyagaw61.github.io/_posts/$(date -Idate)-$1\.md
fi


