#!/bin/sh

hflg=0

if test $# -eq 0 ;then
	hflg=1
fi

while getopts h opt ;do
	case $opt in
		h)hflg=1;;
	esac
done

if test $hflg -eq 1 ;then
	echo 'Usage: mp4abduction [tweet_url]'
	exit 0
fi

echo $1 | sed -E 's@^.*status[^0-9]*(.*)@\1@' > status_id
python $HOME/mgtools/gettweetdata.py $(cat status_id) > data
cat data | sed -E 's@^.*(https://video.twimg.com/.*\.mp4).*$@\1@' > mp4url
wget $(cat mp4url)
rm status_id data mp4url
