#!/bin/sh

hflg=0
#if test $# -eq 0 ;then
#	hflg=1
#fi

for arg in "$@" ;do
	if test "$arg" = "-h" -o "$arg" = "--help" -o "$arg" = "help" ;then
		hflg=1
	fi
done

if test $hflg -eq 1 ;then
	echo -n "Usage: mpinstall
"
	exit 0
fi

#cd $HOME/mgtools
#git pull https://github.com/miyagaw61/mgtools.git

cd $HOME
if test -e $HOME/.mgtools.bak ;then
	rm -rf $HOME/.mgtools.bak
fi
cp -a $HOME/mgtools/ $HOME/.mgtools.bak
mkdir -p $HOME/.mgtools.bak/IGNORE
if test -e $HOME/.mgtools.bak/.gitignore ;then
	cat $HOME/.mgtools.bak/.gitignore | while read var ;do
		cp -a $HOME/.mgtools.bak/$var $HOME/.mgtools.bak/IGNORE
	done
fi
if test -e $HOME/mgtools ;then
	rm -rf $HOME/mgtools
fi
git clone https://github.com/miyagaw61/mgtools.git $HOME/mgtools
cp -a $HOME/.mgtools.bak/.gitignore $HOME/mgtools/.gitignore
cp -a $HOME/.mgtools.bak/IGNORE/* $HOME/mgtools/

