#!/bin/sh

hflg=0
#if test $# -eq 0 ;then
#	hflg=1
#fi

for arg in "$@" ;do
	if test "$arg" = "-h" -o "$arg" = "--help" -o "$arg" = "help" ;then
		hflg=1
	fi
done

if test $hflg -eq 1 ;then
	echo -n "Usage: mpinstall
"
	exit 0
fi

cd $HOME/mgtools
git pull https://github.com/miyagaw61/mgtools.git

#cd $HOME
#if test -e $HOME/mgtools.tmp ;then
#	rm -rf $HOME/mgtools.tmp
#fi
#mkdir $HOME/mgtools.tmp
#if test -e $HOME/mgtools/.gitignore ;then
#	cp -a $HOME/mgtools/.gitignore ./gitignore.tmp
#	cat ./gitignore.tmp | while read var ;do
#		cp -a $HOME/mgtools/$var $HOME/mgtools.tmp/
#	done
#fi
#if test -e $HOME/mgtools ;then
#	rm -rf $HOME/mgtools
#fi
#git clone https://github.com/miyagaw61/mgtools.git $HOME/mgtools
#cp -a $HOME/gitignore.tmp $HOME/mgtools/.gitignore
#cp -a $HOME/mgtools.tmp/* $HOME/mgtools/
#if test -e $HOME/mgtools.tmp ;then
#	rm -rf $HOME/mgtools.tmp
#fi

