#!/bin/sh

if test "$1" = "-h" ;then
	echo "Usage: nowloading [loop_count]"
	exit 0
fi

allrm $usedFile
file='nowloading.tmp'
usedFile=$file
echo '[/]nowloading...' > nowloading.tmp
echo '[-]nowloading...' >> nowloading.tmp
echo '[\\\]Nowloading...' >> nowloading.tmp
echo '[|]nOwloading...' >> nowloading.tmp
echo '[/]noWloading...' >> nowloading.tmp
echo '[-]nowLoading...' >> nowloading.tmp
echo '[\\\]nowlOading...' >> nowloading.tmp
echo '[|]nowloAding...' >> nowloading.tmp
echo '[/]nowloaDing...' >> nowloading.tmp
echo '[-]nowloadIng...' >> nowloading.tmp
echo '[\\\]nowloadiNg...' >> nowloading.tmp
echo '[|]nowloadinG...' >> nowloading.tmp
echo '[/]nowloading...' >> nowloading.tmp
echo '[-]nowloading...' >> nowloading.tmp
echo '[\\\]nowloading...' >> nowloading.tmp
echo '[|]nowloading...' >> nowloading.tmp

if test $# -eq 0 ;then
	i=1
else
	i=$1
fi
while test ! $i -eq 0 ;do
	cat $file | while read var ;do
		writedel $var
	done
	i=$((${i}-1))
done
allrm $usedFile
