#!/bin/sh

if test $# -eq 0 ;then
	echo 'Usage: nsed file before after
 file   : input file name
 before : before
 after  : after'
	exit 0
fi

while getopts h opt ;do
	case $opt in
		h)echo 'Usage: nsed [input_file] [sed_pattern]'; exit 0 ;;
	esac
done

cat $HOME/Documents/git/mgtools/nsed.def | perl -pe 's@ARG1@'$2'@g' > $HOME/Documents/git/mgtools/nsed.tmp.tmp
cat $HOME/Documents/git/mgtools/nsed.tmp.tmp | perl -pe 's@ARG2@'$3'@g' > $HOME/Documents/git/mgtools/nsed.tmp
cat $1 | sed -f $HOME/Documents/git/mgtools/nsed.tmp
rmtmp

