#!/bin/sh

hflg=0

if test $# -eq 0 ;then
	hflg=1
fi

while getopts h opt ;do
	case $opt in
		h)hflg=1;;
	esac
done
shift $(($OPTIND - 1))

if test $hflg -eq 1 ;then
	echo "Usage: pgdb [file]"
	exit 0
fi

gdb -q -x ~/bin/gdbrc -x gdbrc -p $(pgrep -n $1)
