#!/bin/sh

hflg=0

#if test $# -eq 0 ;then
#	hflg=1
#fi

while getopts h opt ;do
	case $opt in
		h)hflg=1;;
	esac
done
shift $(($OPTIND - 1))

if test $hflg -eq 1 ;then
	echo "Usage: "
	exit 0
fi

if test "$(ping -c 1 8.8.8.8 | grep '1 received')" ;then
	if test "$(ping -c 1 google.com | grep '1 received')" ;then
		cecho -rfn '[+]'
		cecho -gf 'OK.'
	else
		cecho -rfn '[+]'
		cecho -rf 'Failed.'
	fi
else
	cecho -rfn '[+]'
	cecho -rf 'Failed.'
fi
