#!/bin/sh

while getopts h opt
do
	case ${opt} in
		h)
		echo "Usage: rp file count
 file  : file name
 count : pop count(-a/all: search 1-4 pop count)"
		exit 0 ;;
	esac
done

if test "$(uname -a | grep x86_64)" ;then
	arch="x64"
else
	arch="x86"
fi

if test "$2" = "-a" -o "$2" = "all" ;then
	rp-lin-$arch -r 20 -f $1 --unique > fullropgadget
	echo '\033[0;34m#----popret----#\033[0;39m'
	cat fullropgadget | while read var;do echo -e $var | grep -o -E 'pop' | wc -l  ;done | grep -n 1 | sed -E 's/^([0-9]*):.*/\1/' > num
	cat num | while read var;do sed -n ${var}P fullropgadget ;done 
	echo '\033[0;34m#----pop2ret----#\033[0;39m'
	cat fullropgadget | while read var;do echo -e $var | grep -o -E 'pop' | wc -l  ;done | grep -n 2 | sed -E 's/^([0-9]*):.*/\1/' > num
	cat num | while read var;do sed -n ${var}P fullropgadget ;done 
	echo '\033[0;34m#----pop3ret----#\033[0;39m'
	cat fullropgadget | while read var;do echo -e $var | grep -o -E 'pop' | wc -l  ;done | grep -n 3 | sed -E 's/^([0-9]*):.*/\1/' > num
	cat num | while read var;do sed -n ${var}P fullropgadget ;done 
	echo '\033[0;34m#----pop4ret----#\033[0;39m'
	cat fullropgadget | while read var;do echo -e $var | grep -o -E 'pop' | wc -l  ;done | grep -n 4 | sed -E 's/^([0-9]*):.*/\1/' > num
	cat num | while read var;do sed -n ${var}P fullropgadget ;done 
	rm fullropgadget
	rm num
else
	echo '\033[0;34m#----pop'$2'ret----#\033[0;39m'
	rp-lin-$arch -r 20 -f $1 --unique > fullropgadget
	cat fullropgadget | while read var;do echo $var | grep -o -E 'pop' | wc -l  ;done | grep -n $2 | sed -E 's/^([0-9]*):.*/\1/' > num
	cat num | while read var;do sed -n ${var}P fullropgadget ;done 
	rm fullropgadget
	rm num
fi

