#!/bin/sh

username=$(cat $HOME/Documents/sharemount.username)
password=$(cat $HOME/Documents/sharemount.password)

while getopts h,d opt
do
	case ${opt} in
	h)
	echo ' $1 : host_IP_addr\n d : default_IP_addr(192.168.44.1)'
	exit 0 ;;
	d)
	echo 'default_IP_addr is 192.168.44.1'
	mount -t cifs -o username=$username,password=$password //192.168.44.1/Share /mnt/windows
	exit 0 ;;
	esac
done

if test $# -eq 0 ;then
	sharemount 192.168.44.1
	exit 0
fi

mount -t cifs -o username=$username,password=$password //$1/Share /mnt/windows
