#!/bin/sh

while getopts h,d opt
do
	case ${opt} in
	h)
	echo ' $1 : host_IP_addr\n d : default_IP_addr(192.168.11.9)'
	exit 0 ;;
	d)
	echo 'default_IP_addr is 192.168.11.9'
	mount -t cifs -o username=user01,password=password_hoge //192.168.11.9/Share /mnt/windows
	exit 0 ;;
	esac
done

if test $# -eq 0 ;then
	sharemount 192.168.44.1
	exit 0
fi

mount -t cifs -o username=user01,password=password_hoge //$1/Share /mnt/windows
echo 'shared' > ~/bin/shared
