#!/bin/sh

username=$(cat $HOME/Documents/sharemount/sharemount.username)
password=$(cat $HOME/Documents/sharemount/sharemount.password)

while getopts h opt
do
	case ${opt} in
		h)echo "Usage: sharemount [ip(def:192.168.44.1)]"; exit 0 ;;
	esac
done

if test $# -eq 0 ;then
	sharemount 192.168.44.1
	exit 0
fi

mount -t cifs -o username=$username,password=$password //$1/Share /mnt/windows
