#!/bin/sh

hflg=0

if test $# -eq 0 ;then
	hflg=1
fi

while getopts h opt ;do
	case $opt in
		h)hflg=1;;
	esac
done
shift $(($OPTIND - 1))

if test $hflg -eq 1 ;then
	echo "Usage: snecho [arg]"
	exit 0
fi

if test $# -eq 1 ;then
	echo "$1" | tr ' ' '\n'
	exit 0
fi

for arg in "$@" ;do
	echo "$arg" | tr ' ' '\n'
done
