#!/bin/sh

if test $# -eq 0 -o "$1" = "-h" ;then
	echo "Usage: whitecat file"
	exit 0
fi

if test $# -eq 1 ;then
	cat $1 | perl -pe 's/.*?\d\dm(.*).\[/\1/g' | perl -pe 's/(.*)\d.\d\dm/\1/g'
	exit 0
fi

for arg in $@ ;do
	echo $arg | perl -pe 's/.*?\d\dm(.*).\[/\1/g' | perl -pe 's/(.*)\d.\d\dm/\1/g'
done

