#!/bin/sh

if test "$1" = "-h" ;then
	echo "Usage: xready [file(def:exploit.py)]"
	exit 0
fi

if test $# -eq 0 ; then
cp -a $HOME/Documents/git/mgtools/pwntools_template.py ./exploit.py
exit 0
fi
cp -a $HOME/Documents/git/mgtools/pwntools_template.py ./$1

