#!/bin/sh

hflg=0

#if $# -eq 0 ;then
#	hflg=1
#fi

while getopts h opt ;do
	case $opt in
		h)hflg=1;;
	esac
done
shift $(($OPTIND - 1))

if test $hflg -eq 1 ;then
	echo "Usage: bkup"
	exit 0
fi

if test $# -eq 1 ;then
	dstPath=$1
elif test $# -eq 0 ;then
	dstPath="/mnt/windows/bk"
fi

if test ! -e /mnt/windows/bk/ ;then
	echo 'please mount.'
	exit 0
fi

cecho -rfn '[+]'
cecho -gf $HOME'/mgtools/ -> '${dstPath}'/mgtools/'
rsync -auv $HOME/repos/mgtools/* ${dstPath}/mgtools/



cecho -rfn '[+]'
cecho -gf $HOME'/ctf/ -> '${dstPath}'/ctf/'
rsync -auv $HOME/ctf/* ${dstPath}/ctf/



cecho -rfn '[+]'
cecho -gf $HOME'/Desktop/ -> '${dstPath}'/Desktop/'
rsync -auv $HOME/Desktop/* ${dstPath}/Desktop/



cecho -rfn '[+]'
cecho -gf $HOME'/Documents/ -> '${dstPath}'/Documents/'
rsync -auv $HOME/Documents/* ${dstPath}/Documents/



cecho -rfn '[+]'
cecho -gf $HOME'/Downloads/ -> '${dstPath}'/Downloads/'
rsync -auv $HOME/Downloads/* ${dstPath}/Downloads/



cecho -rfn '[+]'
cecho -gf $HOME'/neosnippets/ -> '${dstPath}'/neosnippets/'
rsync -auv $HOME/neosnippets/* ${dstPath}/neosnippets/



cecho -rfn '[+]'
cecho -gf $HOME'/tmp/ -> '${dstPath}'/tmp/'
rsync -auv $HOME/tmp/* ${dstPath}/tmp/



cecho -rfn '[+]'
cecho -gf $HOME'/peda/ -> '${dstPath}'/peda/'
rsync -auv $HOME/peda/* ${dstPath}/peda/



cecho -rfn '[+]'
cecho -gf $HOME'/.bashrc -> '$HOME'/mgtools/initial_setting/rc/bashrc'
rsync -auv $HOME/.bashrc $HOME/repos/mgtools/initial_setting/rc/bashrc



cecho -rfn '[+]'
cecho -gf '/usr/share/vim/vimrc -> '$HOME'/mgtools/initial_setting/rc/vimrc'
rsync -auv /usr/share/vim/vimrc $HOME/repos/mgtools/initial_setting/rc/



cecho -rfn '[+]'
cecho -gf $HOME'/mgtools/initialsetting/rc/ -> '${dstPath}'/rc/'
rsync -auv $HOME/repos/mgtools/initial_setting/rc/* ${dstPath}'/rc/'



