#!/bin/sh

hflg=0

if test $# -eq 0 ;then
	hflg=1
fi

while getopts h opt ;do
	case $opt in
		h)hflg=1;;
	esac
done
shift $(($OPTIND - 1))

if test $hflg -eq 1 ;then
	echo "Usage: pgdb [file]"
	exit 0
fi

flg="32"
subflg="64"
if test "$(uname -a | grep x86_64)" ;then
	flg="64"
	subflg="32"
fi

if test "$(file $1 | grep $flg'-bit')" ;then
	gdb -q -x $HOME/repos/mgtools/gdbrc.def -x gdbrc -p $(pgrep -n $1)
else
	mgpedaconf $subflg
	gdb -q -x $HOME/repos/mgtools/gdbrc.def -x gdbrc -p $(pgrep -n $1)
	mgpedaconf $flg
fi

