#!/bin/sh

hflg=0
if test $# -eq 0 ;then
	hflg=1
fi

for arg in "$@" ;do
	if test "$arg" = "-h" -o "$arg" = "--help" -o "$arg" = "help" ;then
		hflg=1
	else
		file=$arg
	fi
done

if test $hflg -eq 1 ;then
	echo -n "Usage: ./"$(basename $0)" [-h] [argfile] [ [arg1][arg2] ]
"
	exit 0
fi

if test $# -eq 1 ;then
    cat $file | grep -e '\-' -e '\+'
elif test $# -eq 2 ;then
    diff -u $1 $2 > watchdiff-arg.tmp
    cat watchdiff-arg.tmp | grep -e '\-' -e '\+'
    allrm watchdiff-arg.tmp
fi
