source $REPOS/mgtools/conf/rc/vim/init/map.vim
source $REPOS/mgtools/conf/rc/vim/init/set.vim
source $REPOS/mgtools/conf/rc/vim/init/functions.vim
source $REPOS/mgtools/conf/rc/vim/init/binary_mode.vim
source $REPOS/mgtools/conf/rc/vim/init/autofcitx.vim
source $REPOS/mgtools/conf/rc/vim/init/au.vim
source $REPOS/mgtools/conf/rc/vim/plugins/dein_trigger.vim
source $REPOS/mgtools/conf/rc/vim/init/paste_indent.vim
source $REPOS/mgtools/conf/rc/vim/init/let.vim
source $REPOS/mgtools/conf/rc/vim/init/closebuf.vim
source $REPOS/mgtools/conf/rc/vim/init/color.vim

