export HOME=/home/miyagaw61
export REPOS=$HOME/repos
export r=$REPOS
export MGTOOLS_ROOT=$REPOS/mgtools
export GRAVE_ROOT=$HOME/tmp/grave

export PATH=$PATH:/usr/local/bin
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$MGTOOLS_ROOT
export PATH=$PATH:$HOME/bin/win32yank-x64
export PATH=$PATH:$HOME/bin/ripgrep-0.7.1-x86_64-unknown-linux-musl
export PATH=$PATH:$HOME/bin/neovim/bin/
export EDITOR="$HOME/bin/neovim/bin/nvim"
export RUSGIT_EDITOR="vim -u NONE -N"
export GIT_NAME='miyagaw61'
export GIT_EMAIL='miyagaw61@gmail.com'
export TERM=xterm-256color
export NVIM_LISTEN_ADDRESS='/tmp/nvimsocket'
export BROWSER='chrome'
export RUST_SRC_PATH="$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/srRc/rust/src"
export DISPLAY=localhost:0.0
