#!/bin/sh

nflg=1
hflg=0
aflg=0

#if test $# -eq 0 ;then
#	hflg=1
#fi

while getopts ha opt ;do
	case $opt in
		h)hflg=1;;
		a)aflg=1;nflg=0;;
	esac
done
shift $(($OPTIND - 1))

if test $hflg -eq 1 ;then
	echo "Usage: twitter [option]
[+]UsageOption:
   a: add_tl
   no_use_option: output"
	exit 0
fi

if test $nflg -eq 1 ;then
	python $HOME/repos/mgtools/twitter.py 1000 >> $HOME/Documents/twitter/tl &
	while test "$(ps aux | grep -P 'python.*/mgtools/twitter.py 1000' | grep -v 'grep')" ;do
		nowloading
	done
	cat $HOME/Documents/twitter/tl | less -MRi
	allrm $HOME/Documents/twitter/tl
	exit 0
fi

if test $aflg -eq 1 ;then
	python $HOME/repos/mgtools/twitter.py 1000 >> ~/Documents/twitter/tl &
	while test "$(ps aux | grep -P 'python.*/bin/twitter.py 1000' | grep -v 'grep')" ;do
		nowloading
	done
	echo Finish!
	exit 0
fi
